### ISSUE TITLE
streamsx==1.14.0a0: TopologyTester not working anymore

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.topology#2328]
```
  File "/home/streamsadmin/anaconda3/lib/python3.6/site-packages/streamsx/topology/tester.py", line 853, in _distributed_wait_for_result
    path = self._fetch_application_logs(ctxtype)
  File "/home/streamsadmin/anaconda3/lib/python3.6/site-packages/streamsx/topology/tester.py", line 863, in _fetch_application_logs
    if stc.ContextTypes.STREAMING_ANALYTICS_SERVICE == ctxtype or stc.ContextTypes.ANALYTICS_SERVICE == ctxtype or stc.ContextTypes.DISTRIBUTED == ctxtype:
AttributeError: type object 'ContextTypes' has no attribute 'ANALYTICS_SERVICE'
```

**Comment by markheger** [comment]
Still not working in streamsx-1.14.2a0

```
  File "/home/streamsadmin/anaconda3/lib/python3.6/site-packages/streamsx/topology/tester.py", line 853, in _distributed_wait_for_result
    path = self._fetch_application_logs(ctxtype)
  File "/home/streamsadmin/anaconda3/lib/python3.6/site-packages/streamsx/topology/tester.py", line 863, in _fetch_application_logs
    if stc.ContextTypes.STREAMING_ANALYTICS_SERVICE == ctxtype or stc.ContextTypes.ANALYTICS_SERVICE == ctxtype or stc.ContextTypes.DISTRIBUTED == ctxtype:
AttributeError: type object 'ContextTypes' has no attribute 'ANALYTICS_SERVICE'
```

 python3 -m streamsx.scripts.info
streamsx==1.14.2a0 (package)
  location: /home/streamsadmin/anaconda36/lib/python3.6/site-packages
Python version:3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0]
PYTHONHOME=/home/streamsadmin/anaconda3
PYTHONPATH=unset
PYTHONWARNINGS=unset
STREAMS_INSTALL=/opt/ibm/InfoSphere_Streams/4.3.0.0
JAVA_HOME=/opt/ibm/InfoSphere_Streams/4.3.0.0/java
