### ISSUE TITLE
Error using `map` transform when 3rd party module does not have __name__ attribute

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#2278]
Using this notebook: https://dataplatform.cloud.ibm.com/exchange/public/entry/view/9fc33ce7301f10e21a9f92039ca60bb7

Below is the topology it creates:
```
from streamsx.topology import topology, context
import random
import json 
import time

# Define operator
periodic_src = periodicSource()
nnm = neural_net_model(net)

# Build Graph
top = topology.Topology("myTop")

stream_ = top.source(periodic_src)
stream_.publish("asdf")

view = stream_.map(nnm).view() #originally uses transform, still got the same error
````

Submitting this application fails because the line that invokes the map transform is using the Pybrain module, which does not have the `__name__` attribute defined:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-13-fb0bcef3f116> in <module>
     14 stream_.publish("asdf")
     15 
---> 16 view = stream_.map(nnm).view()
     17 
     18 # Submit

...<snip>
/user-home/_global_/python-3/streamsx/topology/runtime.py in _inline_modules(fn, modules, constants)
    437             modules[mk] = gv.__name__
    438         elif hasattr(gv, '__module__') and gv.__module__ != '__main__':
--> 439             modules[mk] = gv.__name__, gv.__module__
    440         elif type(gv) == str or type(gv) == int or type(gv) == float or type(gv) == bool:
    441             constants[mk] = gv

AttributeError: 'FeedForwardNetwork' object has no attribute '__name__'
```

**Comment by natashadsilva** [comment]
I got the same issue using a notebook that tries to score with Keras.
See attached. 
[PredictWithKeras_map_error.zip](https://github.com/IBMStreams/streamsx.topology/files/3698845/PredictWithKeras_map_error.zip)

**Comment by natashadsilva** [comment]
Seems to be a regression because it worked in 1.12

**Comment by ddebrunner** [comment]
IN the Keras notebook it's due to a Python bug : https://bugs.python.org/issue36697

If the attribute `self.model` in `LoadKerasModel` was `self._model` then it would work. The bug is that `self.model` is incorrectly seen as a reference to the global variable `model`.

**Comment by natashadsilva** [comment]
Update: When I tried to use PyBrain3 I still got the same error.

**Comment by ddebrunner** [comment]
`neural_net_model` in the pybrain notebook hits the same Python bug, changing `self.net` to `self._net` should resolve it.

**Comment by ddebrunner** [comment]
The Keras notebook does hit a bug that is fixed by PR #2279

**Comment by natashadsilva** [comment]
Ok...so regarding the original error, is it working as expected? Are all classes expected to have the `__name__` attribute defined?

**Comment by ddebrunner** [comment]
The code should be checking for a name, but what is being accessed is not a class, but instead an instance of a class, so it doesn't have `__name__`.

**Comment by ddebrunner** [comment]
Fixed by 1.13.12
