### ISSUE TITLE
Java subscribe() fails on 4.2.0.3 under RH6

### ISSUE THREAD

**Issue by brucegdc** [IBMStreams/streamsx.topology#955]
See question on Streamsdev for more details 
`
 SEVERE: src/function/com/ibm/streamsx/topology/topic/getTopicSubscription.cpp:15: error: no matching function for call to 'appTrc(SPL::[longstringofcharacters], SPL::rstring)'`

Code:
```
public class ImportTopology {
     public static void main(String[]) args) throws Exception {
       Topology topology =- new Topology("TestImport");
       StreamSchema mySchema = Type.Factory.getStreamSchema("tuple<rstring fname, rstring lname, int32 age>");
      SPLStream gotData = SPLStreams.subscribe(topology, "BruceData", mySchema);
      TStream<String> convertData = gotaData.toTupleString();
      convertData.print();
      StreamsContextFactory.getStreamsContext("DISTRIBUTED").submit.topology.get();
  }
````

More detailed errors:
`getTopicSubscription.cpp: In function 'SPL::rstring com::ibm::streamsx::topology::topic::getTopicSubscription(const SPL::rstring&, const SPL::rstring&)': .streamsx.topology.internal.process.ProcessOutputToLogger run

SEVERE: src/function/com/ibm/streamsx.topology/topic/getTopicSubscription.cpp: 15: error: no matching function for call to `appTrc(SPL::BeJyrNI03TS0qui8yKU8syjPJzEvLN01JTSpNNy0pSkx0BQC5eQU5&, SPL::rstring)'

Looks like it's doing some substitution for the spl.Trace enum that's causing the compiler to croak.
`

**Comment by ddebrunner** [comment]
This full code works on 4.2.0.0 on RH6 and x86_64:
```
import com.ibm.streamsx.topology.*;
import com.ibm.streamsx.topology.context.*;
import com.ibm.streamsx.topology.spl.*;
import com.ibm.streams.operator.*;

  public class ImportTopology {
     public static void main(String[] args) throws Exception {
       Topology topology = new Topology("TestImport");
       StreamSchema mySchema = Type.Factory.getStreamSchema("tuple<rstring fname, rstring lname, int32 age>");
      SPLStream gotData = SPLStreams.subscribe(topology, "BruceData", mySchema);
      TStream<String> convertData = gotData.toTupleString();
      convertData.print();

      StreamsContextFactory.getStreamsContext("DISTRIBUTED").submit(topology).get();
  }
  }
```

It was compiled and run like this:
```
cp="$STREAMS_INSTALL/toolkits/com.ibm.streamsx.topology/lib/com.ibm.streamsx.topology.jar:$STREAMS_INSTALL/lib/com.ibm.streams.operator.samples.jar"

javac -cp $cp *.java

java -cp .:$cp ImportTopology
```

**Comment by ddebrunner** [comment]
@brucegdc  The code you pasted was not valid Java code, there is a `=-` in the assignment of topology.

Could you try the code that works above and the build script provided. If that succeeds and your continues to fail then we need to see exactly what is being done.

I'll see if I can get a 4.2.0.3 on RH6 to try out.

**Comment by brucegdc** [comment]
Tried it as above, and it fails both from Streams Studio & command line on RH6.  It *DOES* work on RH7. 
The =- is an artifact of me having to retype instead of cut & paste.

Fails on 4.2.0.2 on RH6 as well as our 4.2.0.3.20170126144354 patch.
Topology toolkits:   1.6-2017032102141,tgz  as well as the one shipped with the patch - 1.4.4
Java - 1.8 build pxz6480sr3fp11-20160817_02 (SR3 FP11)   (shipped with the patch)

.

**Comment by ddebrunner** [comment]
@brucegdc Are you testing on Intel or Power?

**Comment by brucegdc** [comment]
@ddebrunner  Intel

**Comment by ddebrunner** [comment]
It compiles for me on RH6, Intel with 4.2.0.2 and 4.2.0.3.

Not sure what could be going on in your environment.

**Comment by brucegdc** [comment]
I really hate when this happens.  I've got it happening on two completely different environments.   Could it be gcc version?  I've got 4.4.7 on both of mine.

**Comment by ddebrunner** [comment]
gcc 4.4.7 on my systems.

It looks like the code was generated incorrectly, any chance of providing your generated code?

**Comment by ddebrunner** [comment]
Could you get the line of code from `getTopicSubscription.cpp`, at line 15 ?

This is what I get:
```
::SPL::Functions::Utility::appTrc(SPL::BeJyrNI03TS0qyi8yKU8syjPJzEvLN01JTSpNNy0pSkxOBQC5eQu5::debug, (SPL::rstring("Topic filter:") + topic), 
```

Note the '::debug' at the end of the long string.

**Comment by brucegdc** [comment]
That's what I get as well.  Sorry can't cut & paste over.

**Comment by brucegdc** [comment]
And the definition in the type.cpp file is SELF SELF::debug(3);   If that helps

**Comment by brucegdc** [comment]
@ddebrunner Digging further - all the options for no matching function for call to... don't match the signature.   What the function is doing is appTrc(Enum, rstring);   What the compiler is offering as options for SPL::Functions::Utility::appTrc that has those two first are: 

* const SPL::Enum&, const SPL::rstring & , const std::string &, uint32_t

Looks like it's not getting default values for the aspect & whatever the final number is?

**Comment by brucegdc** [comment]
@ddebrunner Any way to tell the java process to keep the intermediate files when it works?  I've tried to stop it on RH7 and it seems to clean itself up before I can see anything.

**Comment by ddebrunner** [comment]
You use the submit with the context Map parameter, and use this:

http://ibmstreams.github.io/streamsx.topology/doc/javadoc/com/ibm/streamsx/topology/context/ContextProperties.html#KEEP_ARTIFACTS

**Comment by ddebrunner** [comment]
How about a simple SPL app with code that invokes `appTrc`?

**Comment by brucegdc** [comment]
Bounced back & forth with the RH6 & RH7.  My RH6 code ends (SPL::rstring("Topic filter:") + topic));  on line 15.    The RH7 ends (SPL::rstring("Topic filter:") + topic), SPL::rstring("/opt/ibm/InfoSphere_Streams/4.2.0.3.20170126142912/toolkits/com.ibm.streasmx.topology/com.ibm.streamsx.topology.topic/topics.spl"), spl::uint32(150U));  

I suspect that's what's going on - the generator is not adding the file and line numbers.
Now why?  That's a good question.

**Comment by brucegdc** [comment]
Simple SPL app invoking appTrc has ::SPL::Functions::Utility::appTrc(SPL::BeJy....::trace, lit$0, lit$1, lit$2);

**Comment by brucegdc** [comment]
On the off chance it was a version issue, I downloaded the 1.6.0 release (the latest release) from this site as a .tar.gz

Extracted it to ~/top in my home directory, and set $cp to point to it.

Compile fails on RH6 4.1.1.1,  RH6 4.2.0.3.2017....
Compile works on RH7 4.2.0.3.20170126....

**Comment by ddebrunner** [comment]
So, just realized that line 15 was continued, so this is what my (working) generated code looks like:
```
::SPL::Functions::Utility::appTrc(SPL::BeJyrNI03TS0qyi8yKU8syjPJzEvLN01JTSpNNy0pSkxOBQC5eQu5::debug, (SPL::rstring("Topic filter:") + topic), SPL::rstring("/homes/hny4/debrunne/InfoSphere_Streams/4.2.0.2/toolkits/com.ibm.streamsx.topology/com.ibm.streamsx.topology.topic/topics.spl"), SPL::uint32(150U));
```

**Comment by ddebrunner** [comment]
Any strange characters in your `$STREAMS_INSTALL` path?

**Comment by kmarsden** [comment]
What is the full red hat 6 version? Is it 6.6 or later?
https://www.ibm.com/support/knowledgecenter/SSCRJU_4.2.0/com.ibm.streams.install.doc/doc/ibminfospherestreams-install-prerequisites-operating-system-rhel-versions.html

**Comment by ddebrunner** [comment]
Somewhat stumped, but a couple of things you could try:

1) We print out the SPL compilation execution, so verify it looks correct. E.g. this is what I see:
```
Apr 04, 2017 7:43:18 PM com.ibm.streamsx.topology.internal.streams.InvokeSc getToolkitPath
INFO: ToolkitPath:/opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.topology
Apr 04, 2017 7:43:18 PM com.ibm.streamsx.topology.internal.streams.InvokeSc invoke
INFO: Invoking SPL compiler (sc) for main composite: testimport::TestImport
Apr 04, 2017 7:43:18 PM com.ibm.streamsx.topology.internal.streams.InvokeSc invoke
INFO: /opt/ibm/InfoSphere_Streams/4.2.0.0/bin/sc --rebuild-toolkits --optimized-code-generation --num-make-threads=4 -M testimport::TestImport -t /opt/ibm/InfoSphere_Streams/4.2.0.0/toolkits/com.ibm.streamsx.topology 

```

2. Submit to the `TOOLKIT` context and then compile the application manually using `sc`. Use a command similar to the one above.

**Comment by ddebrunner** [comment]
@brucegdc Do you have a 4.2 quick start vm to try this on?

**Comment by brucegdc** [comment]
Nothing odd.  It's in /opt/project/InfoSphere_Streams/4.2.0.3.2017012612345
 basically.  Difference from a normal install is use of /opt/projectname
instead of /opt/ibm,  and I do have a soft link in /opt/project called
InfoSphereStreams that points to the full path.

**Comment by ddebrunner** [comment]
Hmmm - sym links - there's an opportunity for issues ...

**Comment by brucegdc** [comment]
Yes.  Works fine in the 4.2.0.0 Quick Start VM

**Comment by brucegdc** [comment]
Symlink is the problem.  Changed my login profile script to reference the full Streams path instead of the symlink and it compiled and ran under RH6.   

Now the question is how to solve that - having a single path thats identical no matter which version of Streams is installed is critical in this environment.

**Comment by ddebrunner** [comment]
is the symlink across file systems?

I just tried a simple symlink and strangely the topology mechanism still used the correct path `/opt/ibm/InfoSphere_Streams/4.2.0.0` rather than the symlink I had set `STREAMS_INSTALL` to.

**Comment by ddebrunner** [comment]
Ok - I can reproduce it, as @brucegdc says, it's `STREAMS_SPLPATH` pointing to the sym link that causes issues, not `STREAMS_INSTALL`.

The topology api uses the canonical path of `STREAMS_INSTALL` for sc which means it always reverts to the real path of sc.

**Comment by ddebrunner** [comment]
@brucegdc In your environment can you see if it works (using topology) if your `STREAMS_SPLPATH` environment variable does not include `$STREAMS_INSTALL/toolkits` in any form. The topology toolkit will add that for you.

I realize that will probably not work for you as you want `STREAMS_SPLPATH`  set correctly for SPL compiles as well, but would be a useful check.

**Comment by brucegdc** [comment]
Yes, if I delete $STREAMS_INSTALL/toolkits from the SPLPATH environment variable it works.  So we have a workaround at least.

**Comment by ddebrunner** [comment]
I entered a defect against IBM Streams. I can reproduce this outside of the topology toolkit using this code:

```
type AA = tuple<int32 a>;

public composite Main {
   graph
   stream<AA> A = com.ibm.streamsx.topology.topic::Subscribe() {
      param
        topic: "what/ever";
        streamType: AA;
   }
}
```

and a compile like:

`sc -M Main -t /dev/shm/install/4.2.0.0/toolkits`

where ` /dev/shm/install` is a sym link to `/opt/ibm/InfoSphere_Streams`.

**Comment by ddebrunner** [comment]
Closing this as it's not an issue with topology toolkit, but an issue with the product.
